# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearBy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearBy

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GoogleSignIn'
pod 'Alamofire'
pod 'Kingfisher'
pod 'Firebase'

end
